<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	
	<ItemGroup>
		<Reference Include="XUnity.AutoTranslator.Plugin.Core">
			<HintPath>packages\XUnity.AutoTranslator.Plugin.Core.dll</HintPath>
		</Reference>
		<Reference Include="XUnity.AutoTranslator.Plugin.ExtProtocol">
			<HintPath>packages\XUnity.AutoTranslator.Plugin.ExtProtocol.dll</HintPath>
		</Reference>
		<Reference Include="XUnity.Common">
			<HintPath>packages\XUnity.Common.dll</HintPath>
		</Reference>
	</ItemGroup>


</Project>
